#!/bin/sh
source /etc/config/hostapd_action

# 1: interface
# 2: action
# 3: mac

case $2 in
	AP-STA-CONNECTED)
		action=connected
		state=home
	;;
	AP-STA-DISCONNECTED)
		action=disconnected
		state=not_home
	;;
esac

case $3 in
	de:dd:5d:e7:24:0b)
		device=IZipuho-iPhone
		user=zip
	;;
	aa:f4:bf:68:17:b4)
		device=IZipuho-iPhoneBig
		user=zip
	;;
	4e:7b:74:e5:7d:f7)
		device=Nika-iPhone
		user=nika
	;;
esac

logger -t hostapd_action $device $action

token=$token
hostname="$(cat /proc/sys/kernel/hostname)"
room=${hostname#$host_prefix}
entity_id=$(echo "device_tracker.${device}_${room}" | tr '-' '_')
url="$HA/api/states/$entity_id"
data=$(cat <<-END
{
"entity_id": "$entity_id",
"state": "$state",
"attributes": {
  "source_type": "router",
  "mac_address": "$3",
  "user": "$user"
}}
END
)

logger -t hostapd_action $device $data

[[ -n $action && -n $device ]] && curl --silent --output /dev/null --user "$user" --oauth2-bearer "$token" --json "$data" "$url"

