#!/bin/sh

APP_NAME=ha-device-tracker

# 1: interface
# 2: action
# 3: mac

#logger -t "$APP_NAME-debug" "RAW: iface=$1 action=$2 mac=$3 args='$*'"


case "$2" in
  AP-STA-CONNECTED)
    action=connected
    state=home
  ;;
  AP-STA-DISCONNECTED)
    action=disconnected
    state=not_home
  ;;
  online)
    action=init_online
    state=home
  ;;
  offline)
    action=init_offline
    state=not_home
  ;;
  *)
    exit 0
  ;;
esac

#logger -t "$APP_NAME-debug" "$action, $state"

. /lib/functions.sh

handle_device() {
        local type="$1"
        local in_mac="$2"
        config_get mac "$type" mac
        config_get user "$type" user
        mac=$(printf '%s' "$mac" | tr '[:upper:]' '[:lower:]')
        in_mac=$(printf '%s' "$in_mac" | tr '[:upper:]' '[:lower:]')
	#logger -t "$APP_NAME-debug" "$type; $user"
        if [ "$mac" = "$in_mac" ]
        then
                device="$type"
        fi
}

config_load "$APP_NAME"
#logger -t "$APP_NAME-debug" "Config loaded"

config_foreach handle_device device "$3"

if [ -n "$device" ] && [ -n "$action" ]
then
        #logger -t "$APP_NAME-debug" "Action!!! $device $action"

        config_get token ha token
        config_get HA ha url
        config_get room network room

        if [ -n "$room" ]
        then
                resolved_room="$room"
        else
                hostname="$(cat /proc/sys/kernel/hostname)"
                config_get host_prefix network host_prefix
                resolved_room=${hostname#$host_prefix}
        fi

        if [ -z "$resolved_room" ]
        then
                logger -t "$APP_NAME" "room is empty for device '$device'"
                exit 1
        fi

        entity_id=$(echo "device_tracker.${device}_${resolved_room}" | tr '-' '_')
        url="$HA/api/states/$entity_id"

data=$(cat <<EOF
{
  "entity_id": "$entity_id",
  "state": "$state",
  "attributes": {
    "source_type": "router",
    "mac_address": "$3",
    "user": "$user",
    "friendly_name": "${device}@${resolved_room}"
  }
}
EOF
)

        logger -t "$APP_NAME" "$device" "$data"

        curl --silent --output /dev/null \
             --header "Authorization: Bearer $token" \
             --header "Content-Type: application/json" \
             --data "$data" "$url"
fi
