#!/bin/sh /etc/rc.common

APP_NAME=ha-device-tracker
ACTION="/etc/$APP_NAME"

USE_PROCD=1
START=31
STOP=20

matches_tracked_iface() {
        local iface="$1"
        local track_all_ifaces
        local iface_pattern

        config_get track_all_ifaces network track_all_ifaces '0'
        config_get iface_pattern network iface_pattern '*-main-*'

        [ "$track_all_ifaces" = "1" ] && return 0

        case "$iface" in
                $iface_pattern)
                        return 0
                ;;
        esac

        return 1
}

set_device_init_presence(){
        local phone="$1"
        local iface
        local mac
        local found_iface

        config_get mac "$phone" mac
        found_iface=none
        for iface in $ifaces
        do
                matches_tracked_iface "$iface" || continue

                if [ "$(hostapd_cli -i $iface sta $mac | head -n 1)" != "FAIL" ]
                then
                        echo "   true"
                        found_iface=$iface
                        break
                fi
        done

        if [ "$found_iface" != "none" ]
        then
                state=online
                logger -t "$APP_NAME-init" "device '$phone' is online on '$found_iface' ($mac)"
        else
                state=offline
                logger -t "$APP_NAME-init" "device '$phone' is offline ($mac)"
        fi

        "$ACTION" "$found_iface" "$state" "$mac"
}

start_service() {
        echo starting

        ifaces=$(hostapd_cli interface | tail -n +3)
        config_load "$APP_NAME"
        for iface in $ifaces
        do
                echo " $iface"
                matches_tracked_iface "$iface" || continue

                procd_open_instance "$iface"
                procd_set_param command hostapd_cli -i "$iface" -a "$ACTION" -r
                procd_set_param stdout 1
                procd_set_param stderr 1
                procd_set_param respawn
                procd_close_instance
        done

	config_foreach set_device_init_presence device

	echo started
}

reload_service() {
        stop
        start
}

service_triggers() {
        procd_add_reload_trigger "$APP_NAME"
}
