#!/bin/sh /etc/rc.common
config_load hostapd_action

USE_PROCD=1
START=31
STOP=20

ACTION=/etc/hostapd_action

start_service() {
#	if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
#		echo 'Service already running'
#		return 1
#	fi
	uci delete hostapd_action.network.iface
	echo starting
	IFS=$'\n'
	for iface in $(hostapd_cli interface | tail -n +3)
	do
		PIDFILE=/var/run/hostapd_action_$iface.pid
		if [[ $iface == *'-main-'* ]]
		then
			hostapd_cli -i $iface -a $ACTION -r -B -P $PIDFILE
			uci add_list hostapd_action.network.iface=$iface
		fi
	done
	uci commit hostapd_action
	unset IFS
	echo started
}

stop_service() {
	echo stop
	#killall -15 $(cat "$PIDFILE") $$ rm -f "$PIDFILE"
	killall -9 hostapd_cli && rm -f /var/run/hostapd_action_*.pid
	echo stoped
}

