#!/bin/sh /etc/rc.common
source /etc/config/hostapd_action

USE_PROCD=1
START=31
STOP=20

ACTION=/etc/hostapd_action

start_service() {
	echo start
	hostapd_cli -i $IFACE -a $ACTION -r -B -P /var/run/hostapd_cli_$IFACE.pid
}

stop_service() {
	killall -9 hostapd_cli
}

